name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'

permissions:
  contents: read

jobs:
  deploy-to-docker-hub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare and push Docker plugin
        run: |
          export NAME="${{ github.actor }}/pyveth"
          export VERSIONS="latest ${GITHUB_REF/refs\/tags\//}"
          ./package.sh
