name: Test

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  unit_test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          ./test_unittest.sh

  integration_test:
    name: Integration tests
    runs-on: ubuntu-latest
    env:
      VERSION: dev
      VERSIONS: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Prepare Docker plugin
        run: |
          ./package.sh

      - name: Run integration tests
        run: |
          ./test_integration.sh
